"""Contenu brut de la feuille Utilities d'un export bm3 HomeByMe (listes
de reference : Product Type, Room Tags, Brands, ...). Recopie tel quel
dans chaque Excel bm3 construit par bm3_builder, et source de la liste
deroulante Product Type de l'interface. La colonne Brands est volontairement
vide (liste propre au client, gardee hors du depot dans brands_local.txt) :
le Brand de chaque produit se saisit a la main. Fichier genere : ne pas
editer a la main, le regenerer depuis un export bm3 recent si besoin."""

HEADER = ('Room Tags', 'Material Tags', 'Style Tags', 'Color Tags', 'Product Type', 'Target Position', 'Opening Shape', 'Manipulation Mode', 'Magnitude', 'Editable', 'Boolean', 'Brands', 'Configurator Ids', 'Parameter Type', 'Columns according to type', 'importExport.headers.utilities.inOut')

ROWS = [
    ('1+Attic', '3+Bamboo', '4+Antique', '5+Beige', '2+Air conditioners', '1+onFloor', '1+Rectangular', '1+Translate', 'No Dimension', 'None', 'true', None, None, 'Real (continuous)', 'Editable|Parameter Translation Key|Magnitude|Default|Values|Values Translation keys', 'in'),
    ('6+Basement', '8+Brick', '9+Asian', '10+Black', '7+Armchairs', '2+onWall', '2+Circular', '2+Rotate', 'Length', 'Read', 'false', None, None, 'Real (discrete)', 'Editable|Parameter Translation Key|Magnitude|Values', 'out'),
    ('11+Bathroom', '13+Cane', '14+Casual', '15+Blue', '12+Wardrobes', '4+free', '3+RectangularWithUpRound', '3+Translate;Rotate', 'Angle', 'Read & Write', None, None, None, 'Real (multi-range)', 'Editable|Parameter Translation Key|Default|Values|Values Translation keys', None),
    ('16+Bedroom', '18+Carpet', '19+Contemporary', '20+Brown', '17+Bars', '8+onSlopedWall', None, '4+Elevate', 'Intensity', None, None, None, None, 'Integer (continuous)', 'Editable|Parameter Translation Key|Values', None),
    ('21+Cellar', '23+Concrete', '24+Country', '25+Green', '22+Base cabinets', '16+onCeiling', None, '5+Translate;Elevate', None, None, None, None, None, 'Integer (discrete)', 'Editable|Parameter Translation Key|Values', None),
    ('26+Dining Room', '28+Fabric', '29+Eclectic', '30+Grey', '27+Accessories', None, None, '6+Rotate;Elevate', None, None, None, None, None, 'Boolean', 'Editable|Parameter Translation Key|Default|Values|Values Translation keys', None),
    ('31+Entertainment Room', '33+Glass', '34+Industrial', '35+Orange', '32+Mirrors', None, None, '7+Translate;Rotate;Elevate', None, None, None, None, None, 'String', 'Editable|Parameter Translation Key|Default|Values|Values Translation keys', None),
    ('36+Entrance', '38+Hardwood', '39+Mediterranean', '40+Pink', '37+Single Sinks', None, None, None, None, None, None, None, None, 'Color', 'Editable|Parameter Translation Key|Allow any value|Default|Values|Tags', None),
    ('41+Garage', '43+Iron', '44+Modern', '45+Red', '42+Double Sinks', None, None, None, None, None, None, None, None, 'Material', 'Editable|Parameter Translation Key|Allow any value|Default|Values|Tags', None),
    ('46+Garden', '48+Laminated', '49+Retro', '50+White', '47+Sinks', None, None, None, None, None, None, None, None, 'Product', None, None),
    ('51+Hallway', '53+Leather', '54+Romantic', '55+Yellow', '52+Storage', None, None, None, None, None, None, None, None, None, None, None),
    ("56+Kid's room", '58+Metal', '59+Rustic', '60+Purple', '57+Bathtubs', None, None, None, None, None, None, None, None, None, None, None),
    ('61+Kitchen', '63+Paint', '64+Traditional', '65+Transparent', '62+Blinds', None, None, None, None, None, None, None, None, None, None, None),
    ('66+Laundry Room', '68+Plastic', '69+Vintage', '70+Other', '67+Bookcases', None, None, None, None, None, None, None, None, None, None, None),
    ('71+Living Room', '73+Rug', '74+Scandinavian', None, '72+Sideboards', None, None, None, None, None, None, None, None, None, None, None),
    ('75+Office', '77+Steel', '577+Art Nouveau', None, '76+Bunk beds', None, None, None, None, None, None, None, None, None, None, None),
    ('78+Outdoors', '80+Stone', '578+Bohemian', None, '79+Ceiling lights', None, None, None, None, None, None, None, None, None, None, None),
    ('81+Toilets', '83+Synthetic', '579+Coastal', None, "82+Children's beds", None, None, None, None, None, None, None, None, None, None, None),
    (None, '85+Tiles', '580+Modern Farmhouse', None, '84+Fireplace tools', None, None, None, None, None, None, None, None, None, None, None),
    (None, '87+Wallpaper', '581+Ethnic', None, '88+Clothes organizers', None, None, None, None, None, None, None, None, None, None, None),
    (None, '89+Wicker', '582+Boho Chic', None, '90+Shoe organizers', None, None, None, None, None, None, None, None, None, None, None),
    (None, '91+Wood', '583+Hollywood Regency', None, '92+Coffee tables', None, None, None, None, None, None, None, None, None, None, None),
    (None, '93+PVC', '584+Mid-Century Modern', None, '94+Cooktops', None, None, None, None, None, None, None, None, None, None, None),
    (None, '95+Fiberglass', '585+Parisian Modern', None, '96+Curtains', None, None, None, None, None, None, None, None, None, None, None),
    (None, '97+Linoleum', '586+Nautical', None, '98+Decorative accessories', None, None, None, None, None, None, None, None, None, None, None),
    (None, '99+Stainless steel', '587+Shabby Chic', None, '100+Desks', None, None, None, None, None, None, None, None, None, None, None),
    (None, '101+Seagrass', '588+Tropical', None, '102+Chairs', None, None, None, None, None, None, None, None, None, None, None),
    (None, '103+Laminate', '589+Zen', None, '104+Tables', None, None, None, None, None, None, None, None, None, None, None),
    (None, '105+Imitation leather', '590+Minimalist', None, '106+Beds', None, None, None, None, None, None, None, None, None, None, None),
    (None, '107+Wainscot', '591+Oriental', None, '108+Double beds', None, None, None, None, None, None, None, None, None, None, None),
    (None, '109+Cement', '592+Art Deco', None, '110+Dressers', None, None, None, None, None, None, None, None, None, None, None),
    (None, '111+Tiling', '604+Pop Art', None, '112+Dryers', None, None, None, None, None, None, None, None, None, None, None),
    (None, '113+Plaster', None, None, '116+Plugs & Meters', None, None, None, None, None, None, None, None, None, None, None),
    (None, '115+Plexiglass', None, None, '118+Electrical switchs', None, None, None, None, None, None, None, None, None, None, None),
    (None, '117+Copper', None, None, '120+TV', None, None, None, None, None, None, None, None, None, None, None),
    (None, '119+Wool', None, None, '122+Electronics & Entertainments', None, None, None, None, None, None, None, None, None, None, None),
    (None, '121+Brass', None, None, '124+Hifi', None, None, None, None, None, None, None, None, None, None, None),
    (None, '123+Paper', None, None, '126+Home cinema', None, None, None, None, None, None, None, None, None, None, None),
    (None, '125+Enamel', None, None, '128+Faucets', None, None, None, None, None, None, None, None, None, None, None),
    (None, '127+Medium density fiberboard', None, None, '130+Fences', None, None, None, None, None, None, None, None, None, None, None),
    (None, '129+Caoutchouc', None, None, '132+Fireplaces', None, None, None, None, None, None, None, None, None, None, None),
    (None, '131+Marble', None, None, '134+Fitness equipments', None, None, None, None, None, None, None, None, None, None, None),
    (None, '133+Mirror', None, None, '136+Floor lamps', None, None, None, None, None, None, None, None, None, None, None),
    (None, '135+Acrylic', None, None, '138+Free shapes', None, None, None, None, None, None, None, None, None, None, None),
    (None, '137+Toplax', None, None, '140+Freezers', None, None, None, None, None, None, None, None, None, None, None),
    (None, '139+Zinc', None, None, '142+Headboards', None, None, None, None, None, None, None, None, None, None, None),
    (None, '141+Porcelain', None, None, '144+High cabinets', None, None, None, None, None, None, None, None, None, None, None),
    (None, '143+Ceramic', None, None, '146+Home automation', None, None, None, None, None, None, None, None, None, None, None),
    (None, '145+Aluminum', None, None, '148+Intercoms', None, None, None, None, None, None, None, None, None, None, None),
    (None, '147+Teck', None, None, '150+House alarms', None, None, None, None, None, None, None, None, None, None, None),
    (None, '149+Melamine', None, None, '152+Smoke detectors', None, None, None, None, None, None, None, None, None, None, None),
    (None, '151+Mahogany', None, None, '154+Hoods', None, None, None, None, None, None, None, None, None, None, None),
    (None, '153+Alder', None, None, '156+Islands & carts', None, None, None, None, None, None, None, None, None, None, None),
    (None, '155+Birch', None, None, '158+Junior chairs', None, None, None, None, None, None, None, None, None, None, None),
    (None, '157+Cedar', None, None, '160+Lightings', None, None, None, None, None, None, None, None, None, None, None),
    (None, '159+Cherry tree', None, None, '162+Microwaves', None, None, None, None, None, None, None, None, None, None, None),
    (None, '161+Oak', None, None, '164+Nursery', None, None, None, None, None, None, None, None, None, None, None),
    (None, '163+Ebony', None, None, '166+Changing tables', None, None, None, None, None, None, None, None, None, None, None),
    (None, '165+Spruce', None, None, '168+Beds & cribs', None, None, None, None, None, None, None, None, None, None, None),
    (None, '167+Maple', None, None, '170+Decorations', None, None, None, None, None, None, None, None, None, None, None),
    (None, '169+Beech', None, None, '172+People', None, None, None, None, None, None, None, None, None, None, None),
    (None, '171+Jatoba', None, None, '174+Pergolas & Gazebos', None, None, None, None, None, None, None, None, None, None, None),
    (None, '173+Larch', None, None, '176+Plants & Flowers', None, None, None, None, None, None, None, None, None, None, None),
    (None, '175+Merbau', None, None, '178+Playgrounds', None, None, None, None, None, None, None, None, None, None, None),
    (None, '177+Walnut', None, None, '180+Plumbing', None, None, None, None, None, None, None, None, None, None, None),
    (None, '179+Charm', None, None, '182+Pools', None, None, None, None, None, None, None, None, None, None, None),
    (None, '181+Chestnut', None, None, '184+Radiators', None, None, None, None, None, None, None, None, None, None, None),
    (None, '183+Cotton', None, None, '186+Ranges', None, None, None, None, None, None, None, None, None, None, None),
    (None, '185+Ash', None, None, '188+Refrigerators', None, None, None, None, None, None, None, None, None, None, None),
    (None, '187+Elm', None, None, '190+Rugs', None, None, None, None, None, None, None, None, None, None, None),
    (None, '189+Apple tree', None, None, '192+Shelves', None, None, None, None, None, None, None, None, None, None, None),
    (None, '193+Clay', None, None, '194+Shower columns', None, None, None, None, None, None, None, None, None, None, None),
    (None, '195+Hemp', None, None, '196+Shower doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, '197+Terracotta', None, None, '198+Showers', None, None, None, None, None, None, None, None, None, None, None),
    (None, '199+Earthenware', None, None, '200+Side tables', None, None, None, None, None, None, None, None, None, None, None),
    (None, '201+Stoneware', None, None, '202+Single beds', None, None, None, None, None, None, None, None, None, None, None),
    (None, '203+Granite', None, None, '204+Sofas', None, None, None, None, None, None, None, None, None, None, None),
    (None, '205+Limestone', None, None, '206+Stools', None, None, None, None, None, None, None, None, None, None, None),
    (None, '207+Glycerophtalic paint', None, None, '208+Table lamps', None, None, None, None, None, None, None, None, None, None, None),
    (None, '209+Microfiber', None, None, '210+Toilets', None, None, None, None, None, None, None, None, None, None, None),
    (None, '211+Wool carpet', None, None, '212+Toys', None, None, None, None, None, None, None, None, None, None, None),
    (None, '213+Sisal', None, None, '214+TV & Media furnitures', None, None, None, None, None, None, None, None, None, None, None),
    (None, '215+Polyamide', None, None, '216+Wall cabinets', None, None, None, None, None, None, None, None, None, None, None),
    (None, '217+Watercolor', None, None, '218+Wall decorations', None, None, None, None, None, None, None, None, None, None, None),
    (None, '219+Fleece', None, None, '220+Wall lamps', None, None, None, None, None, None, None, None, None, None, None),
    (None, '221+Sealed parquet', None, None, '222+Wall shelves', None, None, None, None, None, None, None, None, None, None, None),
    (None, '223+Cobblestone', None, None, '224+Washers', None, None, None, None, None, None, None, None, None, None, None),
    (None, '304+Asphalt', None, None, '225+Benches', None, None, None, None, None, None, None, None, None, None, None),
    (None, '305+Grass', None, None, '226+Small appliances', None, None, None, None, None, None, None, None, None, None, None),
    (None, '306+Polyester', None, None, '227+Sun loungers', None, None, None, None, None, None, None, None, None, None, None),
    (None, '311+Solid wood composite floor ', None, None, '228+Aquarium', None, None, None, None, None, None, None, None, None, None, None),
    (None, '313+Wall cloth', None, None, '229+Coat stands', None, None, None, None, None, None, None, None, None, None, None),
    (None, '314+Clapboards', None, None, '230+Vases', None, None, None, None, None, None, None, None, None, None, None),
    (None, '329+Slate', None, None, '231+Kids activities', None, None, None, None, None, None, None, None, None, None, None),
    (None, '330+Rock', None, None, '232+Beams', None, None, None, None, None, None, None, None, None, None, None),
    (None, '331+Ceramic tiles', None, None, '233+Towel holders', None, None, None, None, None, None, None, None, None, None, None),
    (None, '332+Porcelain tiles', None, None, '234+Ovens', None, None, None, None, None, None, None, None, None, None, None),
    (None, '333+Stone tiles', None, None, '235+Dishwashers', None, None, None, None, None, None, None, None, None, None, None),
    (None, '334+Glass tiles', None, None, '236+Nightstands', None, None, None, None, None, None, None, None, None, None, None),
    (None, '335+Mosaic tiles', None, None, '237+Vehicles', None, None, None, None, None, None, None, None, None, None, None),
    (None, '336+Natural hardwood', None, None, '238+Mailbox', None, None, None, None, None, None, None, None, None, None, None),
    (None, '337+Bleached hardwood', None, None, '239+Trees', None, None, None, None, None, None, None, None, None, None, None),
    (None, '338+Dark hardwood', None, None, '240+Front doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, '339+Patterned carpet', None, None, '241+Security doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, '340+Plain carpet', None, None, '242+Patio doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, '341+Sheet vinyl', None, None, '243+Screen doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, '342+Vinyl tile', None, None, '244+Simple interior doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, '343+Patterned wallpaper', None, None, '245+Double interior door', None, None, None, None, None, None, None, None, None, None, None),
    (None, '344+Plain wallpaper', None, None, '246+Sliding door', None, None, None, None, None, None, None, None, None, None, None),
    (None, "345+Children's wall paper", None, None, '247+Interior door', None, None, None, None, None, None, None, None, None, None, None),
    (None, '346+Kitchen and bathroom wallpaper', None, None, '248+Interior openings', None, None, None, None, None, None, None, None, None, None, None),
    (None, '349+Cork', None, None, '249+Garage doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, '350+Satin paint', None, None, '250+Service doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, '351+Matt paint', None, None, '251+Simple windows', None, None, None, None, None, None, None, None, None, None, None),
    (None, '395+Cushion covers', None, None, '252+Double windows', None, None, None, None, None, None, None, None, None, None, None),
    (None, '396+Chrome', None, None, '253+Simple sliding windows', None, None, None, None, None, None, None, None, None, None, None),
    (None, '397+Curtain fabric', None, None, '254+Double sliding windows', None, None, None, None, None, None, None, None, None, None, None),
    (None, '398+Horizontal picture', None, None, '255+Basement windows', None, None, None, None, None, None, None, None, None, None, None),
    (None, '399+Vertical picture', None, None, '256+Fixed windows', None, None, None, None, None, None, None, None, None, None, None),
    (None, '400+Square picture', None, None, '257+Skylights', None, None, None, None, None, None, None, None, None, None, None),
    (None, '405+Decking', None, None, '259+Stairs', None, None, None, None, None, None, None, None, None, None, None),
    (None, '432+wall tile', None, None, '260+Outdoor activities', None, None, None, None, None, None, None, None, None, None, None),
    (None, '433+Round Rug', None, None, '261+Poufs', None, None, None, None, None, None, None, None, None, None, None),
    (None, '563+Quartz', None, None, '262+Screens', None, None, None, None, None, None, None, None, None, None, None),
    (None, '575+Duvet cover', None, None, '263+Wall stickers', None, None, None, None, None, None, None, None, None, None, None),
    (None, '595+Zellige', None, None, '264+Dressing tables', None, None, None, None, None, None, None, None, None, None, None),
    (None, '596+Shell', None, None, '265+Trash cans', None, None, None, None, None, None, None, None, None, None, None),
    (None, '597+Terrazzo', None, None, '266+Wood burning stoves', None, None, None, None, None, None, None, None, None, None, None),
    (None, '598+Solid Surfaces', None, None, '267+Oven cabinets', None, None, None, None, None, None, None, None, None, None, None),
    (None, '599+Plaster', None, None, '269+Under sink cabinets', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '270+Sliding storage', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '271+Corner cabinets', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '272+Safety detectors', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '273+Openings', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '275+Frames', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '276+Candles', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '277+Candlesticks', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '278+Paintings', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '279+Books', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, "280+Kids' mobiles", None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '281+Height charts', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '282+weathercocks', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '283+Fountains', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '284+Bridges', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '285+Wells', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '286+Columns', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '287+Statues et sculptures', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '288+Water heaterx', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '289+Furnaces/boilers', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '290+Clocks', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '291+Posters', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '292+Swings', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '293+Sandboxes', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '294+Trampolines', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '295+Barbecues', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '296+Gardening', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '297+Patio heaters', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '298+Helical Stairs', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '299+Straight Stairs', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '300+Quaterturn Stairs', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '301+Double Quaterturn Stairs', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '302+kitchen sets', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '307+Folding doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '308+Push windows', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '309+Bay windows', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '316+Kitchenware', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '317+Tableware', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '318+Railings', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '319+Platforms', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '320+Cupboards', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '321+Mattresses', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, "322+Pet's stuff", None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '323+Wine cellars', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '324+Ornaments', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '325+Suspended lamps', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '326+Tapestry', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '328+Meridians', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '348+Towel-dryers', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '352+Toboggan', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '353+Hammock', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '354+Carpets', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '355+Hardwoods', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '356+Wallpapers', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '357+Paints', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '360+Vinyls', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '361+Tiling', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '362+Mosaic', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '364+Stones', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '365+Slate', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '366+Brick', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '367+Concrete', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '368+Marble', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '369+Mirror', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '370+Linoleum', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '371+Shingles', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '372+Fiberboard', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '373+Wall clothes', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '374+Cobblestones', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '375+Footstools', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '376+Showcases', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '377+Leisure chairs', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '379+Office chairs', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '380+Bed stools', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '381+Outdoor sofas', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '382+Outdoor chairs', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '383+Outdoor benches', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '384+Outdoor tables', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '385+Cushions', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '388+Swinging patio doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '389+Sliding patio doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '390+Bathroom mirrors', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '391+Children desks', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '392+Children bedroom furnitures', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '393+Gates', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '394+Wainscot', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '401+Decking tiles', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '403+Decking', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '407+Garden lounges', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '408+Do-it-yourself articles', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '410+Filler strips', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '411+Security products', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '412+Straight sofas', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '413+Corner sofas', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '414+Modular sofas', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '415+Armless chairs', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '416+Four poster beds', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '417+Mezzanine beds', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '418+Floor standing mirrors', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '419+Wall mirrors', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '420+Kitchen accessories', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '421+Baby bathtubs', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '422+Bathroom base cabinets', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '423+Bathroom columns', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '424+Bathroom vanity units', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '425+Bathroom accessories', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '426+Office supplies ', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '427+Cradles', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '428+Children decorations', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '429+Outdoor decorations', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '430+Garden lightings', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '431+Beach umbrellas', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '435+Balconies', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '436+Gravel', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '437+Parging', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '443+Worktops', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '445+Plinths', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '517+Fronts', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '518+Boxes', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '521+Legs', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '534+Wall tiles', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '536+Doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '537+Double doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '538+Double glass doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '539+Drawers', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '540+Glass doors', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '546+Cabinet shelves', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '554+Filler strip angle', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '556+Joint', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '557+Operation', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '558+Wall edge strips', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '559+Wall Panels', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '560+Free standing filler strips', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '561+Deco strips', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '562+Quartz', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '564+Resources', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '565+Cornices', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '566+Countertop edges', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '567+Wall panel edges', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '568+Drainer grooves', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '569+Wall edge strip edges', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '570+Cover panels', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '572+Handles', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '573+Roof windows', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '576+Half height cabinets', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '594+Washer Dryers', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '600+Glass', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '601+Metal', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '602+Plastic', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '603+Panoramic wallpaper', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '605+Wall Molding', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '606+Auto cornices', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '607+Auto plinths', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '608+Wall-hung toilet', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '609+Platform stairs', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '610+Horizontal picture', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '611+Vertical picture', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '612+Square picture', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '613+Base cabinets with double front', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '614+Wall cabinets with double front', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '615+Risers', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '616+Meeting room tables', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '617+Flex office tables', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '618+Workstations', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '619+Signage', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '620+Storage Acoustic panel', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '621+Screen', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '622+Printer', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '623+Fire extingisher', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '624+Unknown material', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '625+Corner boxes', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '626+False ceiling', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '627+Beam', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '628+Electrical plugs', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '629+Style', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '630+Feature', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '631+Construction material', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '632+Textile', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '633+Leather', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '634+Wood', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '635+Resin', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '636+Rock', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '637+Paper', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '638+Shutter', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '639+Unknown', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '640+Single-material ashlar and rubble (granite, porphyry, limestone, sandstone, millstone, shale, volcanic stone)', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '641+Ashlar and rubble stone (granite, porphyry, limestone, sandstone, millstone, shale, volcanic stone) with rubble fill', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '642+Pisé or stabilised earth concrete', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '643+Wooden slabs without fill', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '644+Wooden slabs with fill', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '645+Wooden logs', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '646+Single solid bricks', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '647+Double solid brick with air gap', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '648+Hollow bricks', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '649+Cellular clay bricks', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '650+Solid concrete blocks', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '651+Hollow concrete blocks (breeze blocks)', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '652+Concrete blocks', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '653+Machefer concrete', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '654+Cellular concrete < 2013', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '655+Cellular concrete >= 2013', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '656+Concrete/insulation/concrete sandwich', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '657+Timber frame', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '658+Polycarbonate panel', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '659+Paving stone/glass brick', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '660+Glass wool', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '661+Rock wool', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '662+Wood wool', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '663+Hemp wool', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '664+Cotton wool', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '665+Expanded cork', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '666+Wood fibre', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '667+Expanded or extruded polystyrene', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '668+Phenolic foam', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '669+Polyurethane foam', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '670+Plasterboard', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '671+Solid brick', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '672+Hollow brick', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '673+Solid plaster tiles', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '674+Alveolar plaster tiles', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '675+Solid concrete blocks', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '676+Perforated concrete blocks', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '677+Hollow concrete blocks (breeze blocks)', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '678+Plaster', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '679+Concrete coating', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '680+Lime coating', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '681+Insulating coating', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '682+Daub', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '683+Tiles, ceramics', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '684+Decorative brick cladding', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '685+Wood panelling', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '686+PVC cladding', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '687+Stone cladding', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '688+Other', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '689+Concrete coating', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '690+Lime coating', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '691+Insulating coating', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '692+Daub', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '693+Concrete slab', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '694+Tiles, ceramics', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '695+Decorative brick cladding', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '696+Wood cladding', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '697+PVC cladding', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '698+Stone cladding', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '699+Meta cladding', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '700+Flooring with or without infill', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '701+Floor between wooden joists with or without infill', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '702+Shingles and infill', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '703+Wood flooring on wood joists', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '704+Floor between metal joists with or without infill', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '705+Wood flooring on metal joists', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '706+Voutains on metal joists', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '707+Heavy floorboards such as terracotta joists or concrete beams', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '708+Brick or rubble stone joists', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '709+Concrete slab', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '710+Insulated joist floor', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '711+Ceiling with or without infill', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '712+Ceiling between wooden joists with or without infill', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '713+Shingles and infill', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '714+Wood ceiling under wood joists', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '715+Wood ceiling over wood joists', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '716+Ceiling between metal joists with or without infill', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '717+Wood ceiling over metal joists', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '718+Wood ceiling under metal joists', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '719+Heavy ceilings such as terracotta floor joists or concrete beams', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '720+Concrete slab', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '721+Zinc', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '722+Steel sheet', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '723+Flat tiles', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '724+Channel tiles', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '725+Synthetic rubber', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '726+Slate', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '727+Stubble', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '728+Wood', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '729+Classic gas boiler (before 1991)', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '730+Standard gas boiler (after 1991)', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '731+Low-temperature gas boiler', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '732+Condensing gas boiler', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '733+Gas radiator', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '734+Classic oil boiler (before 1991)', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '735+Standard oil boiler (after 1991)', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '736+Low temperature oil boiler', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '737+Condensing oil boiler', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '738+Log boiler', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '739+Pellet boiler', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '740+Log-burning stove', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '741+Pellet stove', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '742+Heat network', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '743+Electric boiler', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '744+Electric convector heaters', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '745+Storage electric heaters', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '746+Electric radiant heater', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '747+Electric underfloor heating', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '748+Electric ceiling heating', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '749+Solar heating', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '750+Air/air heat pump', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '751+Air-to-water, geothermal or water-to-water heat pump - before 2008', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '752+Air-to-water, geothermal or water-to-water heat pump - 2008-2014', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '753+Air-to-water, geothermal or water-to-water heat pump - 2015-2016', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '754+Air-to-water, geothermal or water-to-water heat pump - after 2017', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '755+Water radiator', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '756+Heated ceiling', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '757+Underfloor heating', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '758+Forced air', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '759+Direct emission (stove, electric radiator, etc.)', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '760+Niche', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '761+US Refrigerator', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '762+Integrated Refrigerator', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '763+Island Hood', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '764+Integrated Hood', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '765+Deco Hood', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '766+Integrated Dishwashers', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '767+Integrated Washers', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '768+Integrated Dryers', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '769+Appliance Panel', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '770+Illuminated Shelf', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '771+Illumination', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '772+Bottle Rack', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '773+Pilaster', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '774+Side panel', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '775+Sub Assemblies', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '776+Fan', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '777+Electric switchboard', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '778+Solar panel', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '779+Electrical plug', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '780+Camera', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '781+Trellis arch', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '782+Outdoor floor lamp', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '783+Outdoor lighting', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '784+String light', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '785+Patterned rug', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '786+Door mat', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '787+Linen', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '788+Candle accessory', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '789+DIY accessory', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '791+Creative hobby', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '792+Musical instrument', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '793+Entry accessory', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '794+Animal', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '795+Outdoor rug', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '796+Doormat', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '797+Runner rug', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '798+Outdoor wall lamp', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '800+Outdoor string light', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '801+Outdoor pet accessories', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '802+Game room games', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '803+Ceiling fan', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '804+Soil', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '805+Mulch', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '806+Roof tile', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '807+Additional items', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '808+Basket', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '809+Holiday decorations', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '810+Clothes', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '811+Freestanding waterfalls', None, None, None, None, None, None, None, None, None, None, None),
    (None, None, None, None, '812+Freestanding Ovens', None, None, None, None, None, None, None, None, None, None, None),
]


def column(name):
    """Valeurs non vides d'une colonne (ex. column("Product Type"))."""
    i = HEADER.index(name)
    return [row[i] for row in ROWS if i < len(row) and row[i] not in (None, "")]


PRODUCT_TYPES = column("Product Type")
